pipeline {
    agent any

    tools {
        maven "Maven 3.9.3"
        jdk "jdk11"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /usr/share/mvn"
            }
        }
    }
    stages {
         stage ('Build') {
              steps {
                     sh 'mvn clean package'
       }
      }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
